////////////////MOVIES:////////
//post
###
POST http://localhost:3000/api/movies HTTP/1.1
Content-Type: application/json

{
    "mov_id": 1,
    "mov_title": "lolito",
    "mov_year": "1997",
    "mov_time": 58,
    "mov_lang": 25,
    "mov_dt_rel": "octubre,1995",
    "mov_rel_country": "Colombia"
}

